version: "3.7"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      SPIGOT_DOWNLOAD_URL: "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
      TYPE: "SPIGOT"
      CONSOLE: "FALSE"
      BUILD_FROM_SOURCE: "true"
    ports:
      - 25565:25565
      - 4711:4711
      - 25575:25575
    volumes:
      - mcdata:/data
    restart: unless-stopped
  mcdata:
    image: kaveh8000/mcdata
    volumes:
      - mcdata:/data
  setup:
    image: kaveh8000/mcdata:setup
    volumes:
      - setup:/setup
volumes:
  mcdata:
  setup:
